Upgrades h5py requirement
Was getting some strange errors:

2018-01-10 21:43:37,380 DEBG 'pdp_frontend' stdout output:
ERROR:pdp.error:Exception raised during streamed response: ('cannot import name _errors',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 66, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 27, in accept
    client, addr = listener.accept()
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
error: [Errno 11] Resource temporarily unavailable

which were referred to here:
https://github.com/h5py/h5py/pull/558

and this seems to take care of it.